services:
  api:
    build: .
    environment:
        ASPNETCORE_Kestrel__Certificates__Default__Path: /usr/local/share/ca-certificates/aspnetapp.pfx
        ASPNETCORE_Kestrel__Certificates__Default__Password: "123"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      